### ISSUE TITLE
Inline Images from wordpress are too small

### ISSUE THREAD

**Issue by ch264** [postmanlabs/postman-blog#46]

**Comment by mclausaudio** [comment]
I wonder if this issue is on that specific blog post / certain posts... others seem to look the appropriate size

![Screen Shot 2020-02-26 at 10 26 27 AM](https://user-images.githubusercontent.com/14118422/75375291-a6768780-5882-11ea-9cea-cfd68621a6c5.png)
![Screen Shot 2020-02-26 at 10 26 36 AM](https://user-images.githubusercontent.com/14118422/75375295-a8d8e180-5882-11ea-8b42-29454c3e5e45.png)
![Screen Shot 2020-02-26 at 10 27 02 AM](https://user-images.githubusercontent.com/14118422/75375297-a9717800-5882-11ea-8797-a8ff137890e2.png)

**Comment by ch264** [comment]
Yes I saw that. This is the data that comes back from wordpress. TBH I do not know where images are stored in wordpress

**Comment by ch264** [comment]
Images come from wordpress. Wpgraphql does not bring back all the image data that is available on wordpress. 
Maybe we can reach out to the community and check with Jason Bahl what the roadmap is for images through wpgraphql

**Comment by ch264** [comment]
This is a ticket for content team
